
package org.tango.cassandra_monitor_client.tools;

/**
 * HTML code to display Release Notes for this package.
 * It is generated by Pogo classes from a text file.
 */

public interface ReleaseNotes {
	String htmlString = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<html>\n" + 
		"<head>\n" + 
		"<title> Release Notes </title>\n" + 
		"</head>\n" + 
		"<body text=\"#000000\" bgColor=\"#FFFFFF\" link=\"#0000FF\" vLink=\"#7F00FF\" aLink=\"#FF0000\">\n" + 
		"<p><!-------TITLE------></p>\n" + 
		"<center><h2> Release Notes </h2>\n" + 
		"generated: 30-05-2018  10:01</center>\n" + 
		"<li><b>CassandraMonitor-2.1 - 30/05/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Remove \'Compaction History\' option (not available any more in device)<br>" + 
		"&nbsp; &nbsp; &nbsp; Add an animated gif for compaction<br>" + 
		"<li><b>CassandraMonitor-2.0 - 27/02/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Replace CassandraDistribution device class by connection information.<br>" + 
		"&nbsp; &nbsp; &nbsp; Add hdb_tables package and display.<br>" + 
		"<li><b>CassandraMonitor-1.7 - 23/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Data protection bug fix.<br>" + 
		"<li><b>CassandraMonitor-1.6 - 18/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; ATK ErrorHistory and Diagnostics added.<br>" + 
		"&nbsp; &nbsp; &nbsp; Refresh button on SS Tables window.<br>" + 
		"<li><b>CassandraMonitor-1.5 - 09/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve table display for Hdb tables info.<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve error management.<br>" + 
		"<li><b>CassandraMonitor-1.4 - 08/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; HDB table sizes and SS tables displayed for each table on each node.<br>" + 
		"<li><b>CassandraMonitor-1.3 - 05/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; SS tables added.<br>" + 
		"&nbsp; &nbsp; &nbsp; HDB table sizes added<br>" + 
		"<li><b>CassandraMonitor-1.2 - 04/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Compaction pending and history added.<br>" + 
		"<li><b>CassandraMonitor-1.1 - 20/12/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Client requests monitoring added<br>" + 
		"<li><b>CassandraMonitor-1.0 - 19/12/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Initial revision<br>" + 
		"</body>\n" + 
		"</html>\n"
	;
}