
package org.tango.cassandra_monitor_client.tools;

/**
 * HTML code to display Release Notes for this package.
 * It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote {
	String str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<html>\n" + 
		"<head>\n" + 
		"<title> Release Note </title>\n" + 
		"</head>\n" + 
		"<body text=\"#000000\" bgColor=\"#FFFFFF\" link=\"#0000FF\" vLink=\"#7F00FF\" aLink=\"#FF0000\">\n" + 
		"<p><!-------TITLE------></p>\n" + 
		"<center>	<h2>CassandraMonitoring Release Notes </h2>\n" + 
		"	(Generated 18-01-2018  09:18:57)</center><br>\n" + 
		"<li><b>CassandraMonitor-1.6 - 18/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; ATK ErrorHistory and Diagnostics added.<br>" + 
		"&nbsp; &nbsp; &nbsp; Refresh button on SS Tables window.<br>" + 
		"&nbsp; &nbsp; &nbsp; Bug fixes.<br>" + 
		"<li><b>CassandraMonitor-1.5 - 09/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Improve table display for Hdb tables info.<br>" + 
		"&nbsp; &nbsp; &nbsp; Improve error management.<br>" + 
		"<li><b>CassandraMonitor-1.4 - 08/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; HDB table sizes and SS tables displayed for each table on each node.<br>" + 
		"<li><b>CassandraMonitor-1.3 - 05/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; SS tables added.<br>" + 
		"&nbsp; &nbsp; &nbsp; HDB table sizes added<br>" + 
		"<li><b>CassandraMonitor-1.2 - 04/01/18:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Compaction pending and history added.<br>" + 
		"<li><b>CassandraMonitor-1.1 - 20/12/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Client requests monitoring added<br>" + 
		"<li><b>CassandraMonitor-1.0 - 19/12/17:</b><br>" + 
		"&nbsp; &nbsp; &nbsp; Initial revision<br>" + 
		"</body>\n" + 
		"</html>\n"
	;
}